# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('strength', models.FloatField()),
                ('smoke', models.FloatField()),
                ('taste', models.FloatField()),
                ('heat', models.FloatField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
