# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
