# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0002_auto_20170420_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='heat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='release_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='smoke',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='strength',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='taste',
            field=models.FloatField(null=True),
        ),
    ]
