# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import tobacco.models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0003_auto_20170420_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='image',
            field=models.ImageField(null=True, upload_to=tobacco.models.PathAndRename('tobacco/static/tobacco/')),
        ),
    ]
