# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import tobacco.models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0004_auto_20170422_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='heat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tobacco.models.PathAndRename('tobacco/static/tobacco/')),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='smoke',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='taste',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
