# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0005_auto_20170422_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobacco',
            name='heat_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tobacco',
            name='rating_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tobacco',
            name='smoke_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tobacco',
            name='strength_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tobacco',
            name='taste_votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
