# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import tobacco.models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0006_auto_20170423_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_votes', models.IntegerField(default=0, null=True)),
                ('pub_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='image',
            field=models.ImageField(default='tobacco/static/tobacco/tobaccos/empty_tobacco.png', null=True, storage=tobacco.models.TobaccoStorage(), upload_to=tobacco.models.PathAndRename('tobacco/static/tobacco/tobaccos/')),
        ),
        migrations.AddField(
            model_name='mix',
            name='tobaccos',
            field=models.ManyToManyField(to='tobacco.Tobacco'),
        ),
    ]
