# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import user_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('b_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(default='user_page/static/user_page/avatars/default_avatar.svg', null=True, upload_to=user_page.models.PathAndRename('user_page/static/user_page/avatars/'))),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_page.User', unique=True)),
            ],
        ),
    ]
