# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import user_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0003_auto_20170623_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user_page.models.PathAndRename('user_page/static/user_page/avatars/')),
        ),
    ]
