# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import user_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0001_initial'),
        ('user_page', '0004_auto_20170623_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=user_page.models.AvatarStorage(), upload_to=user_page.models.PathAndRename('user_page/static/user_page/avatars/')),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='auth_page.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='auth_page.User'),
        ),
    ]
