# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0001_initial'),
        ('user_page', '0005_auto_20170703_0031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('follower', 'following')]),
        ),
    ]
