# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco_page', '0003_auto_20170623_1755'),
        ('auth_page', '0001_initial'),
        ('user_page', '0006_auto_20170703_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_vote', models.SmallIntegerField(blank=True, null=True)),
                ('smoke_vote', models.SmallIntegerField(blank=True, null=True)),
                ('taste_vote', models.SmallIntegerField(blank=True, null=True)),
                ('heat_vote', models.SmallIntegerField(blank=True, null=True)),
                ('rating_vote', models.SmallIntegerField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('tobacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tobacco_page.Tobacco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_page.User')),
            ],
        ),
    ]
