# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0009_auto_20170710_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'UserInfo', 'verbose_name_plural': 'UserInfos'},
        ),
        migrations.AlterModelOptions(
            name='usermix',
            options={'verbose_name': 'UserMix', 'verbose_name_plural': 'UserMixes'},
        ),
        migrations.AlterModelOptions(
            name='usertobacco',
            options={'verbose_name': 'UserTobacco', 'verbose_name_plural': 'UserTobaccos'},
        ),
    ]
