# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import tobacco_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_votes', models.IntegerField(default=0, null=True)),
                ('pub_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mixes',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('release_date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('strength', models.FloatField(blank=True, null=True)),
                ('strength_votes', models.IntegerField(default=0)),
                ('smoke', models.FloatField(blank=True, null=True)),
                ('smoke_votes', models.IntegerField(default=0)),
                ('taste', models.FloatField(blank=True, null=True)),
                ('taste_votes', models.IntegerField(default=0)),
                ('heat', models.FloatField(blank=True, null=True)),
                ('heat_votes', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_votes', models.IntegerField(default=0)),
                ('image', models.ImageField(default='tobacco/static/tobacco/tobaccos/empty_tobacco.png', null=True, storage=tobacco_page.models.TobaccoStorage(), upload_to=tobacco_page.models.PathAndRename('tobacco/static/tobacco/tobaccos/'))),
            ],
        ),
        migrations.AddField(
            model_name='mix',
            name='tobaccos',
            field=models.ManyToManyField(related_name='mixes', to='tobacco_page.Tobacco'),
        ),
    ]
