# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import tobacco_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='image',
            field=models.ImageField(default='tobacco_page/static/tobacco_page/tobaccos/empty_tobacco.png', null=True, storage=tobacco_page.models.TobaccoStorage(), upload_to=tobacco_page.models.PathAndRename('tobacco_page/static/tobacco_page/tobaccos/')),
        ),
        migrations.AddField(
            model_name='tag',
            name='tobacco',
            field=models.ManyToManyField(related_name='tags', to='tobacco_page.Tobacco'),
        ),
    ]
