# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco_page', '0002_auto_20170506_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
