# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco_page', '0003_auto_20170623_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='tobaccos',
        ),
    ]
