# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco_page', '0004_remove_mix_tobaccos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixTobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tobacco_page.Mix')),
                ('tobacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tobacco_page.Tobacco')),
            ],
        ),
        migrations.AddField(
            model_name='mix',
            name='tobaccos',
            field=models.ManyToManyField(related_name='mixes', through='tobacco_page.MixTobacco', to='tobacco_page.Tobacco'),
        ),
    ]
